"""公共资源仓库的 manifest、路径和 Git 同步入口。"""

from .acceleration import (
    BUILTIN_GITHUB_ACCELERATION_PREFIXES,
    GITHUB_ORIGIN_PREFIX,
    GithubAccelerationMode,
    accelerate_github_url,
    build_git_instead_of_config,
    normalize_github_repository_url,
    normalize_http_base_url,
    resolve_github_acceleration_prefix,
)
from .encyclopedia import (
    AliasCatalog,
    EncyclopediaResourceError,
    EncyclopediaResourceStore,
    GuideAsset,
)
from .generation import (
    ResourceGenerationError,
    ResourceGenerationManager,
    ResourceGenerationValidator,
    ResourceLease,
    ResourceSnapshot,
    ResourceSnapshotCoordinator,
)
from .git import (
    DEFAULT_RESOURCE_REMOTE,
    GitCommandError,
    GitCommandResult,
    GitUnavailableError,
    ResourceBranchMismatchError,
    ResourceLocalChangesError,
    ResourceRemoteMismatchError,
    ResourceSyncError,
    ResourceSynchronizer,
    ResourceSyncResult,
    download_all_resources,
    run_git,
)
from .manifest import (
    RUNTIME_RESOURCE_DIRECTORIES,
    ResourceManifest,
    ResourceManifestError,
)
from .paths import (
    PLUGIN_NAME,
    RESOURCE_GENERATION_STATE_NAME,
    RESOURCE_GENERATIONS_NAME,
    RESOURCE_REPOSITORY_NAME,
    default_resource_repository_dir,
    resource_generation_state_path,
    resource_generations_dir,
    resource_repository_dir,
)
from .resolver import ResolvedAsset, RuntimeAssetResolver

__all__ = [
    "BUILTIN_GITHUB_ACCELERATION_PREFIXES",
    "DEFAULT_RESOURCE_REMOTE",
    "GITHUB_ORIGIN_PREFIX",
    "PLUGIN_NAME",
    "RESOURCE_GENERATIONS_NAME",
    "RESOURCE_GENERATION_STATE_NAME",
    "RESOURCE_REPOSITORY_NAME",
    "RUNTIME_RESOURCE_DIRECTORIES",
    "AliasCatalog",
    "EncyclopediaResourceError",
    "EncyclopediaResourceStore",
    "GitCommandError",
    "GitCommandResult",
    "GitUnavailableError",
    "GithubAccelerationMode",
    "GuideAsset",
    "ResolvedAsset",
    "ResourceBranchMismatchError",
    "ResourceGenerationError",
    "ResourceGenerationManager",
    "ResourceGenerationValidator",
    "ResourceLease",
    "ResourceLocalChangesError",
    "ResourceManifest",
    "ResourceManifestError",
    "ResourceRemoteMismatchError",
    "ResourceSnapshot",
    "ResourceSnapshotCoordinator",
    "ResourceSyncError",
    "ResourceSyncResult",
    "ResourceSynchronizer",
    "RuntimeAssetResolver",
    "accelerate_github_url",
    "build_git_instead_of_config",
    "default_resource_repository_dir",
    "download_all_resources",
    "normalize_github_repository_url",
    "normalize_http_base_url",
    "resolve_github_acceleration_prefix",
    "resource_generation_state_path",
    "resource_generations_dir",
    "resource_repository_dir",
    "run_git",
]
