"""Rendering facade exposing infrastructure rendering components."""

from ..infrastructure.rendering import (
    AssetRenderError,
    CheckinRenderer,
    ClipRect,
    EncyclopediaRenderer,
    HtmlRenderError,
    HtmlRenderErrorKind,
    HtmlRenderer,
    NoticesRenderer,
    PlayerRenderer,
    RenderResultError,
    RenderSpec,
    RenderedCheckinImage,
    RenderedEncyclopediaImage,
    RenderedNoticesImage,
    RenderedPlayerImage,
    ResourceMap,
    T2IRenderError,
    TemplateRenderError,
    build_profile_header,
    font_data_uri,
    image_data_uri,
    optimized_image_data_uri,
    pil_image_data_uri,
    render_qr_code,
    to_data_uri,
    unicode_font_data_uris,
)
from ..infrastructure.rendering import (
    assets as assets,
    checkin as checkin,
    encyclopedia as encyclopedia,
    errors as errors,
    fonts as fonts,
    notices as notices,
    payloads as payloads,
    player as player,
    qr as qr,
    renderer as renderer,
    spec as spec,
)

__all__ = [
    "AssetRenderError",
    "CheckinRenderer",
    "ClipRect",
    "EncyclopediaRenderer",
    "HtmlRenderError",
    "HtmlRenderErrorKind",
    "HtmlRenderer",
    "NoticesRenderer",
    "PlayerRenderer",
    "RenderResultError",
    "RenderSpec",
    "RenderedCheckinImage",
    "RenderedEncyclopediaImage",
    "RenderedNoticesImage",
    "RenderedPlayerImage",
    "ResourceMap",
    "T2IRenderError",
    "TemplateRenderError",
    "assets",
    "build_profile_header",
    "checkin",
    "encyclopedia",
    "errors",
    "font_data_uri",
    "fonts",
    "image_data_uri",
    "notices",
    "optimized_image_data_uri",
    "payloads",
    "pil_image_data_uri",
    "player",
    "qr",
    "render_qr_code",
    "renderer",
    "spec",
    "to_data_uri",
    "unicode_font_data_uris",
]
